XcodesOrg/xcodes

Makefile, Sources/XcodesKit/XcodeManager.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
Changes signing prefix and keychain service ID from ca.brandonevans.xcodes to com.robotsandpencils.xcodes. Also changes application support directory from Application Support/ca.brandonevans.xcodes to Application Support/com.robotsandpencils.xcodes and will migrate the data if the old directory exists and the new one doesn't. These were both done in order to finish up the move from github.com/interstateone to github.com/robotsandpencils, and I wanted to get it done before the next release is made, which uses the keychain service ID.
Testing:
Resolves #38
=> Change signing prefix, keychain service ID and application support directory

Package.resolved, Package.swift
Fixes the warning on install/build from KeychainAccess
```
warning: PackageDescription API v3 is deprecated and will be removed in the future; used by package(s): KeychainAccess
```
Updated to 3.2 - which improves compatibility with Swift 5. 
Resolved #41
=> #38 update keychain dependency

Sources/xcodes/main.swift
- Updates `Error: Swift.Error` to be `XcodesError` to be a little more detailed on what error is throwing it. 
- Inherited from `LocalizedError` so that `XcodesError` can show a friendlier string. 
So instead of 
`The operation couldn’t be completed. (Error.invalidVersion("10.2.2"))`
it will show
`Version 10.2.2 does not exist`
Totally open for some better wording (perhaps longer) on those error messages.
=> Updates xcodes main errors to be more user friendly

Sources/XcodesKit/Version+Xcode.swift, Sources/XcodesKit/XcodeManager.swift, Tests/XcodesKitTests/Version+XcodeTests.swift, Tests/XcodesKitTests/XcodesKitTests.swift, Tests/XcodesKitTests/developer.apple.com-download-19-6-9.html
Closes #48.
I'm currently seeing Xcode 11 fail the `spctl` Gatekeeper check, and this PR is not intending to address that. See #50.
=> Support developer.apple.com/download redesign

Sources/XcodesKit/Models.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
Xcode 11 beta 1 fails the Gatekeeper check (`spctl`). This PR improves the error message shown from:
`The operation couldn’t be completed. (Error.failedSecurityAssessment)`
to:
```
Xcode 11.0.0 failed its security assessment with the following output:
/Applications/Xcode-11.0.0-beta.app: rejected (invalid destination for symbolic link in bundle)
It remains installed at /Applications/Xcode-11.0.0-beta.app if you wish to use it anyways.
```
Resolves #50.
=> Improve Gatekeeper error message

Sources/XcodesKit/Configuration.swift, Sources/XcodesKit/Models.swift, Sources/XcodesKit/Path+.swift, Sources/XcodesKit/URLSession+Promise.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeList.swift, Sources/XcodesKit/XcodeManager.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
XcodeManager had a lot of responsibilities and a poor name, so this PR intends to fix that. XcodeManager is now XcodeList, and provides arrays of available and installed Xcodes. This better differentiates it from XcodeInstaller, which focuses on the download and install process. The Configuration type and some extensions have been moved into more appropriate places too.
**How to test:**
It should be sufficient to make sure that the `xcodes list`, `xcodes installed`, and `xcodes update` commands continue to work as expected. You can run these with `swift run COMMAND`.
=> Refactor to better define boundaries

Sources/XcodesKit/Environment.swift, Sources/XcodesKit/FileManager+.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/Environment+Mock.swift, Tests/XcodesKitTests/XcodesKitTests.swift
This changes the installation behaviour to move XIPs to the Trash after Xcode has been installed to /Applications instead of immediately deleting them. This more closely matches the steps users take when downloading Xcode XIPs manually, but more importantly it provides a way to recover from installation issues without downloading the (very large) XIPs all over again.
```
$ .build/release/xcodes install 11 beta 4
Downloading Xcode 11.0.0-beta.4+11M374r: 195%
Xcode archive Xcode-11.0.0-beta.4+11M374r.xip has been moved to the Trash.
Xcode 11.0.0-beta.4+11M374r failed its security assessment with the following output:
/Applications/Xcode-11.0.0-beta.4.app: rejected (invalid destination for symbolic link in bundle)
It remains installed at /Applications/Xcode-11.0.0-beta.4.app if you wish to …
```
=> Move XIPs to Trash instead of immediately deleting them

Makefile
Two primary changes:
- Code signing now ensures the binary is run with the [hardened runtime](), making it less likely that xcodes could be exploited for malicious purposes on a users computer by restricting what it can do. These new restrictions shouldn't affect xcodes' features, and during testing it worked as before.
- Signing with a timestamp is a [requirement for notarization](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution#3087727). It's currently [not possible](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow#3087720) (FB6885253) to notarize a standalone executable, but I'd like to be ready to support this if/when it becomes possible.
I also made a small change …
=> Sign with hardened runtime and timestamp

Sources/XcodesKit/Version+Xcode.swift, Tests/XcodesKitTests/Version+XcodeTests.swift
The important change here is to the regular expression used to parse version strings so that it supports multi-word prerelease identifiers like "GM seed". It treats all words as one identifier, like "gm-seed", followed by any prerelease version identifiers like "4" in "gm seed 4".
Another small change is to capitalize "gm" as "GM" instead of "Gm".
**Testing:**
You should try to install 11 GM seed 2 while you have GM seed 1 installed at `/Applications/Xcode-11.0.0-gm.app`, or `/Applications/Xcode-11.0.0-gm-seed.1.app`
(Note I had GM seed 1 installed already as `/Applications/Xcode-11.0.0-gm.app`, which is the `11.0 GM (11A419c) (Installed)` in the list below. It's GM prerelease identifier is taken from the filename, which is why it isn't `11.0 GM Seed 1 (11A419c) (Installed)`.)
```
$ swift …
```
=> Improve GM seed version parsing and descriptions

Sources/XcodesKit/Version+.swift, Sources/XcodesKit/XcodeList.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/Version+XcodeTests.swift
Starting with Xcode 11 beta 6, developer.apple.com/download and developer.apple.com/download/more both list (some) pre-release versions of Xcode. Previously, pre-release versions only appeared on developer.apple.com/download. /download/more doesn't include build numbers, so we trust that if the version number and prerelease identifiers are the same as one on /download then they're the same build. If an Xcode version is listed on both sites then we prefer the one on /download because the build metadata is used later to compare against installed Xcodes.
Because pre-release versions that are installed also have build metadata, but this won't be the case for pre-release versions listed on /download/more, we also need to replace versions that are available with the installed ones with build …
=> Consolidate versions from both download sites

Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
When shell commands failed a helpful error message wasn't always provided to the user. We've had a bunch of users fail during the unxip step because they don't have enough disk space, and while the xip tool does normally output this failure reason it wasn't being passed along by Xcode's.
This change improves some specific XcodeInstaller.Error cases and their error messages. Not all Current.shell command failures are caught and turned into XcodeInstaller.Error, though, so this also improves the fallback behaviour by printing all of the output from Process.PMKError.execution, which was omitted by default.
Testing:
```sh
touch test.xip
git checkout master
swift run xcodes install 11 --url ./test.xip
[3/3] Linking ./.build/x86_64-apple-macosx/debug/xcodes
Failed executing: `/usr/bin/xip …
```
=> Improve output for errors from underlying shell commands

Makefile, README.md, notarize.sh
This adds a makefile directive and script that notarizes the zip file that was already being created. I've already notarized existing releases back to 0.7.0, which you can test by running this command: `spctl -a -vvv -t install $(which xcodes) 2>&1 | grep Notarized`. You should see the output "source=Notarized Developer ID" if you have version 0.7.0 or later installed.
**Testing:**
You'll need to be in our ASC team. I'm not sure if you need a specific role. You'll also need to know the ASC provider value for your account if it's a member of more than one team, which is explained [here](https://indiestack.com/2019/09/notarization-provider-ids/). You could also just sort of take my word for it for now since I'm the only person making releases (😬), but if you want to make sure this works and …
=> Automate notarization

Sources/AppleAPI/URLRequest+Apple.swift
The URLs we were using were originally from the xcode-install project and had been working up until today (2019/11/12). These URLs [were updated](https://github.com/fastlane/fastlane/pull/14509) in that project (actually in fastlane, which it uses for auth) about 7 months ago but I didn't notice this. I started to look in a web inspector while signing in to developer.apple.com and saw that the Olympus session URL changed. [Dave DeLong noted](https://github.com/RobotsAndPencils/xcodes/issues/83#issuecomment-553207943) that a slightly different URL worked for the iTC service key, which is also what [xcinfo uses](https://github.com/xcodereleases/xcinfo/blob/e51f022db3584be884b5d10d8b161ac26dbbee0b/Sources/OlympUs/OlympUs.swift#L213).
**Testing**
1. Delete the `com.robotsandpencils.xcodes` …
=> Update Apple auth URLs

.swiftpm/xcode/xcshareddata/xcschemes/xcodes.xcscheme, README.md, Sources/xcodes/main.swift
It was previously not clear how to specify versions of Xcode to install. The current version argument parsing is sort of incidentally a little fuzzy, and so there are sometimes different ways to specify a single pre-release version like "11.2.1 GM Seed", such as "11.2.1GM Seed". This change adds examples to the command help and to the project README in order to give examples of install commands for pre-release versions. I don't think this is totally sufficient and there is more to be done, but it's a first step.
Resolves #80
=> Improve command documentation

Sources/XcodesKit/Entry+.swift, Sources/XcodesKit/Environment.swift
This changes Files.installed Xcodes to ignore app bundles that don't contain Info.plist files at the expected location instead of crashing. This change doesn't include a test to verify the new behaviour because the Entry type in the Path library doesn't have an accessible initializer, which is required to construct some test data without creating what I thought would be too many workarounds for testing's sake.
Manual test steps:
1. Create a directory in /Applications with a unique name like `Xcode.app` or `Xcode-12.app`.
1. `make`
1. `.build/release/xcodes list` should print the list of available and installed Xcodes and not crash
Closes #87
=> Ignore malformed Xcode app bundles

Package.resolved, Sources/XcodesKit/DateFormatter+.swift, Sources/XcodesKit/Foundation.swift, Sources/XcodesKit/Models.swift, Sources/XcodesKit/Version+.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeList.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
This should be really handy during beta season because you can keep using the same command to get the latest version. 
The separate universal Xcode builds, which versions parse into Version structs a little strangely, means the implementation is a little more involved. The Version struct for `12.0 For Macos Universal Apps Beta 2` sorts last, which is not what we want when `12.0 Beta 4` was released later. In order to mitigate this xcodes now parses the release date or modified date for available Xcode versions, and sorts prerelease versions according to their dates instead of their Versions. This seems to work well, and so the following output for these commands is:
```
❯ swift run xcodes install --latest
Updating...
Latest non-prerelease version available is 11.6
11.6 is already …
```
=> Add install flags for --latest and --latest-prerelease

Sources/XcodesKit/XcodeInstaller.swift, Tests/XcodesKitTests/Fixtures/LogOutput-DamagedXIP.txt, Tests/XcodesKitTests/XcodesKitTests.swift
This addresses #92, where xcodes tries to use an existing XIP but then fails if it's somehow damaged. Now, it'll remove the damaged XIP and retry once. If the user provided the path to the XIP then it'll just exit with an error without removing the XIP, so the user can decide what to do with it. I don't think it makes sense to retry more than once, since I can't imagine e.g. downloading a damaged XIP twice and _then_ getting a good one.
A couple changes were made to support this:
- Break up the main `install` method to make it easier to retry
- Catch the Process.PMKError early and map it to a more specific error. This might be good to do for other shell errors, and would remove the need for handling Process.PMKError specially in the install command in main.swift
A test was added to cover …
=> Retry installation when it fails because of damaged XIP

README.md, Sources/XcodesKit/Aria2CError.swift, Sources/XcodesKit/Environment.swift, Sources/XcodesKit/Promise+.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeList.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
By default, xcodes will use a URLSession to download the specified version. If [aria2](https://aria2.github.io) (available in Homebrew with `brew install aria2`) is installed, either at /usr/local/bin/aria2c or at the path specified by the --aria2 flag, then it will be used instead. aria2 will use up to 16 connections to download Xcode 3-5x faster (based on a couple tests on my residential internet). If you have aria2 installed and would prefer to not use it, you can use the --no-aria2 flag.
aria2 downloads should retry up to 3 times if it fails in the middle, just like URLSession. Errors that cause aria2c to exit with a non-zero status code will show an appropriate error message.
In order to support both aria2 and URLSession, I had to change the download URLs. The previous URL prefix …
=> Add support for downloading with aria2 if it's already installed

Sources/XcodesKit/Version+.swift, Sources/XcodesKit/XcodeSelect.swift, Tests/XcodesKitTests/Version+XcodeTests.swift
If a short version is provided, xcodes will select a matched one if
there is only a single match found in the machine. This allows, for
example, if user has Xcode 12.0 GM Seed installed and has no other 12.0
installed, `xcodes select 12.0` will select it.
Fixes https://github.com/RobotsAndPencils/xcodes/issues/114.
=> Allow selecting with short version

Sources/XcodesKit/Models+FirstWithVersion.swift, Sources/XcodesKit/Models.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeSelect.swift, Tests/XcodesKitTests/Models+FirstWithVersionTests.swift
This PR extracts the behaviour added in #115, which allows users to omit prerelease identifiers (like "beta 2") in command arguments when it's unambiguous, and uses it in the install and uninstall commands. If the version is ambiguous then it should fail.
First, clone this repo if necessary and check out the PR branch:
```
git clone https://github.com/RobotsAndPencils/xcodes.git
cd xcodes
git checkout -b interstateone-116-fuzzy-install-uninstall master
git pull https://github.com/interstateone/xcodes.git 116-fuzzy-install-uninstall
```
Right now there's a 12.3 beta available, and with this change you should be able to install it without specifying the beta identifier:
```
swift run xcodes update
swift run xcodes install 12.3
```
The tests that were added provide examples of how this …
=> Allow somewhat fuzzy version matching for install and uninstall commands

Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift
Small change that I've found helpful and more concise than using "--url" flag for command "install" is "--path" flag. "--url" implies that it's possible to specify a remote URL where the downloaded version would be put. But the actual implementation doesn't take this into account while relying on Path dependency (which makes total sense)
=> renamed --url flag to --path for consistency

Sources/XcodesKit/Environment.swift, Sources/xcodes/main.swift
This changes where xcodes looks for the aria2c executable from the hard-coded `/usr/local/bin/aria2c`, which is where Homebrew will install it, to all of the directories in the user's PATH environment variable. The motivation for this is twofold:
- Homebrew will be changing it's "prefix" (where it installs things) as it adds support for Apple Silicon
- xcodes should support users who use other package managers like MacPorts, or who have manually installed aria2 to some other directory in their PATH
First, clone this repo if necessary and check out the PR branch:
```
git clone https://github.com/RobotsAndPencils/xcodes.git
cd xcodes
git checkout -b interstateone-search-path-for-aria2c master
git pull https://github.com/interstateone/xcodes.git search-path-for-aria2c
```
If you already have …
=> Search PATH for aria2c

.github/workflows/ci.yml
The package bug this was working around has been fixed in Xcode 12.2, which is now available on GitHub's hosted runners. That CI is green here should be sufficient to prove it works as intended.
=> Use Xcode 12.2 and revert to swift test command

Sources/XcodesKit/XcodeInstaller.swift, Tests/XcodesKitTests/Fixtures/LogOutput-IncorrectSavedPassword.txt, Tests/XcodesKitTests/XcodesKitTests.swift
If the ENV password is incorrect, the `loginWithNeeded` method will fail in a recurring loop. This change will ensure that STDIN input is required if authentication fails the first time. Also, the current username is printed out on the password input line for improved clarity.
=> fix(XcodeInstaller): Infinite auth fail loop

Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
Closes #112 
Sometimes it's useful to just download Xcode xip without expanding it.
The implemented solution shows progress as:
`xcodes download 12.0
(1/1) Downloading Xcode 12.0.0: 5 %`
where 1/6 step indicator is replaced by 1/1 depending on the used command (install vs. download)
When the download is finished, the following message appears:
`Xcode 12.0.0 has been downloaded to /Users/<#redacted#>/Library/Application Support/com.robotsandpencils.xcodes/Xcode-12.0.0.xip`
Flags and arguments are exactly as in "install" command, as such the actual code that creates "install" command is reused for both "download" and "install", and depending on the "shouldInstall" flag, one of two is created with appropriate --help configuration and other strings.
=> download command to download without installing/expanding

README.md, Sources/XcodesKit/Environment.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeSelect.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/Environment+Mock.swift, Tests/XcodesKitTests/Fixtures/LogOutput-AlternativeDirectory.txt, Tests/XcodesKitTests/XcodesKitTests.swift
This adds a directory argument at the top level (so it affects all commands) which determines the directory that xcodes installs in to. It defaults to /Applications, which is the current behaviour. xcodes will also check for a value in the XCODES_DIRECTORY environment variable. It applies to installation but also the other commands, so that e.g. selecting or uninstalling a version looks in the desired directory.
The motivation for all of this is to support users that may not want to store Xcode versions in /Applications, for example if they don't have enough space on their boot volume.
This also aligns with the addition of the directory argument as part of #121.
First, clone this repo if necessary and check out the PR branch:
```
git clone https://github.com/RobotsAndPencils/xcodes.git
cd …
```
=> Add directory argument

Package.resolved, Package.swift, README.md, Sources/xcodes/ParsableArguments+LegibleError.swift, Sources/xcodes/main.swift
I have a slight preference for using the first-party library for this because it seems to be more actively developed.
This PR was a draft for a long time because I was waiting to see if SAP would implement fuzzy command suggestions like Guaka has. (SAP does have this for options.) But I'd rather get this merged instead of constantly rebasing it on other changes, and yank the bandaid off. I don't think the lack of this feature is a dealbreaker for adoption, and it might even motivate me to (try to) implement it. 🙃 
What does this change?
- shell completions are supported
- help text has different formatting than what Guaka printed
- fuzzy command suggestions aren't implemented in SAP yet, so errors when you mistype a command are unhelpful
This doesn't change any of the commands, options, …
=> Replace Guaka with swift-argument-parser

README.md, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeSelect.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
This adds the possibility to uninstall a specific Xcode version by running `xcodes uninstall` and then interactively select which version to uninstall.
This reuse the code used to interactively select a specific Xcode version.
Some tests has also been added.
=> Uninstall Interactively

Sources/XcodesKit/XcodeInstaller.swift
This change addresses #23 by adding the path of installed Xcode versions to the output of the `installed` command.
=> Prints Xcode path for installed versions

Package.resolved, Package.swift, Sources/XcodesKit/DataSource.swift, Sources/XcodesKit/Models+FirstWithVersion.swift, Sources/XcodesKit/Version+.swift, Sources/XcodesKit/Version+Xcode.swift, Sources/XcodesKit/Version+XcodeReleases.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeList.swift, Sources/XcodesKit/XcodeSelect.swift, Sources/xcodes/DataSource+ExpressibleByArgument.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/Fixtures/Stub.version.plist, Tests/XcodesKitTests/Models+FirstWithVersionTests.swift, Tests/XcodesKitTests/Version+XcodeTests.swift, Tests/XcodesKitTests/XcodesKitTests.swift
This adds support for [Xcode Releases](https://xcodereleases.com) as a data source for available Xcode versions, and makes it the default. It's still possible to use the Apple data source by providing the `--data-source=apple` option. The motivation for this is that while the data is unofficial it is more complete and reliable than scraping the Apple Developer website. This code is all taken from (with some small changes) [Xcodes.app](https://github.com/RobotsAndPencils/XcodesApp).
Two other changes come along with this:
- Previously build identifiers (for example "12C33" for the final 12.3 release) were only shown for non-final release versions. I think there's value in showing this for all versions since sometimes you need to figure out exactly what versions are installed or available, …
=> Add support for and default to Xcode Releases data source

Sources/XcodesKit/Environment.swift, Sources/XcodesKit/XcodeInstaller.swift, Tests/XcodesKitTests/Environment+Mock.swift, Tests/XcodesKitTests/XcodesKitTests.swift
The intent of #23 was to make it possible to get the path of installed Xcodes more easily, which was implemented by #133. I realized after I wrote the description of that issue that it should be possible to both make the output nice for humans and also make it easy to pipe to other commands to get the paths for scripting purposes. This PR makes that change.
If standard output is an interactive terminal, which is what you'll see most of the time as a user, space will be added between the two columns so that it's easy to read. If standard output is not an interactive terminal, like when you pipe the output to another command or a file, then no spaces will be added and the current behaviour of adding a tab character will be used.
The expected behaviour is below, which you can try out to …
=> Align installed command output into columns for interactive terminals

Package.resolved, Package.swift, Sources/AppleAPI/Client.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeSelect.swift, Sources/xcodes/ParsableArguments+LegibleError.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/Fixtures/LogOutput-FullHappyPath-NoColor.txt, Tests/XcodesKitTests/XcodesKitTests.swift
This adds Rainbow as a dependency for coloured output.
I find this helps in two situations:
- When looking at a long list of information, like output from `xcodes list`, it's easier to visually scan for lines that are coloured in some way. In this specific case, Installed is printed in blue and Selected is printed in green.
- Warnings, errors and success during long-running processes, like downloading and installing, are easier to identify at a glance when it's coloured yellow, red, or green, respectively.
|list|installed|select|error|no color|
|-----|-----|-----|-----|-----|
| <img width="306" alt="Screen Shot 2021-02-02 at 7 31 18 PM" src="https://user-images.githubusercontent.com/594059/106689592-7a34b200-658d-11eb-9ec4-261804c3f353.png"> | <img width="656" alt="Screen Shot 2021-02-02 …
=> Add support for coloured output

Sources/XcodesKit/XcodeInstaller.swift, Tests/XcodesKitTests/Fixtures/LogOutput-FullHappyPath-NonInteractiveTerminal.txt, Tests/XcodesKitTests/XcodesKitTests.swift
This change disables download progress output if `xcodes` isn't running in an interactive terminal. In an interactive terminal `xcodes` will update the same line with progress from 0-100%. In a non-interactive terminal `xcodes` used to write 100 separate lines with the ANSI escape codes, and now it'll only print `(1/6) Downloading Xcode X.Y.Z` once.
This is not the only change that should be made for better support of non-interactive terminals (for example #128, or any other use of readline), but it's a start.
=> Don't output download progress when in a non-interactive terminal

README.md, Sources/AppleAPI/Client.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
Addresses enhancement #136
A new `signout` command has been added to:
* Remove all Keychain items
* Remove cookies in the shared URLSession
* Set `defaultUsername` in Configuration to nil
=> Add signout command

Sources/xcodes/main.swift
I'm currently trying to uninstall Xcode 12.5 Beta 3 using `xcodes`, but it fails with the following error:
```bash
$ xcodes uninstall 12.5 Beta 3
The operation couldn’t be completed. (ExitCode(rawValue: 1))
```
Upon investigating the cause, I discovered that the error is not correctly forwarded, which is why I can't see the _real_ error message. This PR fixes that and forwards the catched errors.
=> Forward legible errors

README.md
=> Fix broken link to `swift-argument-parser`

Sources/XcodesKit/Version+Xcode.swift, Tests/XcodesKitTests/Version+XcodeTests.swift
=> Fixing issue with downloading Release Candidate builds

Makefile
Close #170
@MattKiazyk Might want to test this before merging. It looks like **maybe** the output executable might be in a different location. But since I'm not completely familiar with the build/distribution system of this project, I'm not sure that matters.
I was able to verify that the outputted executable from this PR does produce a universal binary tho.
Please let me know if any adjustments need to be made.
=> Setting universal build

Sources/xcodes/ParsableArguments+InstallError.swift, Sources/xcodes/main.swift
When running `xcodes install x.x.x` if the Xcode version is already installed, do not exit(1). Instead, exit with a success.
Addresses https://github.com/RobotsAndPencils/xcodes/issues/142
Example:
=> Do not exit(1) if xcode is already installed

.swiftpm/xcode/xcshareddata/xcschemes/xcodes-Package.xcscheme, Package.swift, Sources/Unxip/Unxip.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift
This mirrors this change in Xcodes.app:  https://github.com/RobotsAndPencils/XcodesApp/pull/179
In my tests (M1 Max, 64GB RAM), unxipping is 3x faster than `/usr/bin/xip`. I measured unxipping Xcode 13.3 beta 3 twice with the flag on (~100s) and off (~300s).
To use this, you need to be running macOS 11 or later, and pass the `--experimental-unxip` flag to an `xcodes install` command.
E.g.
```
xcodes install --latest --experimental-unxip
```
=> Add experimental unxip flag

.github/workflows/ci.yml, Tests/XcodesKitTests/Fixtures/LogOutput-AlternativeDirectory.txt, Tests/XcodesKitTests/Fixtures/LogOutput-DamagedXIP.txt, Tests/XcodesKitTests/Fixtures/LogOutput-FullHappyPath-NoColor.txt, Tests/XcodesKitTests/Fixtures/LogOutput-FullHappyPath-NonInteractiveTerminal.txt, Tests/XcodesKitTests/Fixtures/LogOutput-FullHappyPath.txt, Tests/XcodesKitTests/Fixtures/LogOutput-IncorrectSavedPassword.txt
There were unit tests that broke due to recent changes. Fixing the broken fixture files and also changing the CI to use Xcode 13 as that is now required to build the package
=> Fix broken unit tests due to new logs and Xcode version

Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
The steps that require superuser (root) permissions are optional, so we can add a flag to skip them. This also makes `xcodes` more interactive (we don't need to stop to ask the user for its credentials).
This closes  https://github.com/RobotsAndPencils/xcodes/issues/177.
=> Added `no-superuser` flag

Sources/Unxip/Unxip.swift
This update comes from these two commits (the second of which seems important to me):
- saagarjha/unxip@d7cd61aa099b9cadd8955dc761464e88cbe28033 - Be a bit more frugal with our compression buffer
- saagarjha/unxip@ab0ccc398bf91e01e8ddb563e649a9584db05684 - Wait to create parent directory before linking
=> update unxip to the latest version

Makefile
trying to fix warning message comes from `swift build` during installation with `brew`.
`"warning: '--build-path' option is deprecated; use '--scratch-path' instead"`
reason: https://github.com/apple/swift-package-manager/pull/4195
=> Update Makefile - refactor swift-build option

Sources/XcodesKit/XcodeInstaller.swift, Sources/xcodes/main.swift, Tests/XcodesKitTests/XcodesKitTests.swift
Added a new `--empty-trash` flag to `xcodes install` and `xcodes uninstall`, to completely delete Xcode's .xip or the app itself instead of keeping it on the user's Trash.
This closes #185.
=> Added support to immediately delete Xcode and its XIPs

Sources/XcodesKit/Models.swift, Sources/XcodesKit/URLRequest+Apple.swift, Sources/XcodesKit/XcodeInstaller.swift
I hate having to log into my Apple Developer account, always having to put in my 2fa code, when I want to download Xcode, but Apple has never given us the ability to do so.
As a CI user, it sucks that I have to type in my credentials all the time, while trying to do a xcode install on multiple machines. 
This PR changes that.
By using a public URL provided by Apple, we can get a token cookie that can be used to download the version of Xcode that we wish, without having to provide a log in. 🎉 
Caveats:
- This does not work when using the `Apple` datasource. More specifically that token doesn't work for listing the Xcode versions with `https://developer.apple.com/services-account/QH65B2/downloadws/listDownloads.action`
=> Add ability to download Xcode without logging in using XcodeRelease

Sources/XcodesKit/XcodeSelect.swift
If the currently requested xcode is already selected, there is no need to prompt the user to give sudo permissions and re-select the path. We can just avoid the step and exit early.
Closes https://github.com/RobotsAndPencils/xcodes/issues/102
=> Exit immediately if trying to select currently selected xcode

README.md, XCODE_VERSION.md
This document was largely copied by the now-archived fastlane.ci repository: https://github.com/fastlane/ci/blob/master/docs/xcode-version.md and also based on https://github.com/xcpretty/xcode-install/pull/424 where I added the same file: https://github.com/xcpretty/xcode-install/blob/master/XCODE_VERSION.md
I updated the language and references to xcode-install to `xcodes`.
I believe we should still try and make this a standard in the iOS community, hence why I'm creating this PR, to give a bit more life and exposure to this great feature.
It's amazing to see that xcodes already support it 💪 Great job!
=> Add documentation for the `.xcode-version` file

Sources/XcodesKit/Environment.swift, Sources/XcodesKit/XcodeList.swift, Tests/XcodesKitTests/Environment+Mock.swift
After running the unit tests while working on #226, I noticed `xcodes list` was returning fake versions of Xcode. It looks like this is actually a pre-existing issue with the unit tests, so I figured I'd open a separate PR to fix it.
=> Use mocks when writing the cache file in unit tests

Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeSelect.swift, Sources/xcodes/App.swift
Adds options `--select` and `--update` to `install` command.
Details
---
* Uses #181 as base because without that the `--select` option will always ask user for password even if the Xcode version is already selected
* I'm not that fluent in `PromiseKit` so happy to make any improvements
* Creating this as a draft until we can get #181 merged
* Closes #161
=> Add select option to install

Sources/XcodesKit/Version+Xcode.swift, Sources/XcodesKit/XcodeInstaller.swift, Sources/XcodesKit/XcodeSelect.swift, Sources/xcodes/App.swift, Tests/XcodesKitTests/XcodesKitTests.swift
=> Update select command to use .xcode-version

Sources/XcodesKit/XcodeInstaller.swift
In Sept 2022, Xcodes was updated to use the same mechanism that is used to download runtimes with no login, to download Xcode. 
ie: https://developerservices2.apple.com/services/download?path=/Developer_Tools/tvOS_16.1_Simulator_Runtime/tvOS_16.1_Simulator_Runtime.dmg returns 200 to set the `ADCDownloadAuth` cookie to be able to download
As of mid Nov 2022, Apple has return 403 (forbidden) for this endpoint for Xcode versions only. Runtimes still return 200. 
https://developerservices2.apple.com/services/download?path=/Developer_Tools/Xcode_14.0.1/Xcode_14.0.1.xip
I'm not sure if this is deliberate from Apple (My guess is it is), but this PR reinstates the old way of download xcodes as all libraries and utilities have done for years now.
I don't think Apple will ever allow this open …
=> restore downloading via xcodereleases with apple username/password :(

Sources/XcodesKit/Downloader.swift, Sources/XcodesKit/Environment.swift, Sources/XcodesKit/Promise+.swift, Sources/XcodesKit/XcodeInstaller.swift
If a new Apple ID account doesn't accept Developer Agreement at https://developer.apple.com/ then Xcode download will fail with Unauthorized error
However, the way Apple handles unauthorized errors is by redirecting to https://developer.apple.com/unauthorized/ and happily returning 200. Therefore the only way to check for authorization is to catch this redirect. If we don't do this, then unauthorized html will be downloaded and attempted to be unxipped, so the xcodes will fail with a "corrupted xip" error.
Therefore this PR:
1. Attempts to catch unauthorized redirect and throw error
2. Adds a descriptive message when this error is thrown
3. Prevents retries in case of 403. Retrying won't help, so it's better to terminate early
How to test:
1. In the `XcodeInstaller.swift` replace all …
=> Better Handling of Apple Unauthorized errors

Sources/XcodesKit/Downloader.swift, Sources/XcodesKit/RuntimeInstaller.swift, Sources/xcodes/App.swift, Tests/XcodesKitTests/Fixtures/LogOutput-Runtime_NoBetas.txt, Tests/XcodesKitTests/Fixtures/LogOutput-Runtimes.txt
Resolves #262.
Also changed the word "Downloaded" to "Installed" in the runtimes list to avoid confusion.
=> Add a download runtimes command

Sources/AppleAPI/Client.swift, Sources/AppleAPI/Hashcash.swift, Sources/AppleAPI/URLRequest+Apple.swift, Tests/AppleAPITests/AppleAPITests.swift, Tests/AppleAPITests/Fixtures/Login_2FA_Succeeds/Federate.json, Tests/XcodesKitTests/XcodesKitTests.swift
Apple requires the `X-APPLE-HC` header now when signing in to https://idmsa.apple.com/appleauth/auth/signin. 
Leaving out this header results in Apple ID's possibly getting locked out, where the only way to get them back is to rest the Apple ID Password
Thanks to [arielmichaeli](https://twitter.com/arielmichaeli) for the figuring out the tough parts!
=> Implement hashcash for AppleID Authentication

.swiftpm/xcode/xcshareddata/xcschemes/xcodes.xcscheme, Sources/XcodesKit/Models+Runtimes.swift, Tests/XcodesKitTests/Fixtures/DownloadableRuntimes.plist, Tests/XcodesKitTests/Fixtures/LogOutput-Runtime_NoBetas.txt, Tests/XcodesKitTests/Fixtures/LogOutput-Runtimes.txt, Tests/XcodesKitTests/RuntimeTests.swift
Closes #299 
Adds support for proper parsing of `com.apple.platform.xros` - ie: VisionOS. 🥽 
With this change you can use`xcodes runtimes install "visionOS 1.0-beta1"`
=> feat: add support for VisionOS download

Sources/AppleAPI/Client.swift
Attempted to report the correct error for accounts that have hardware keys. Obviously doesn't fix https://github.com/XcodesOrg/xcodes/issues/279 but hopefully makes it a little clearer to folks.
=> Show proper error when authenticating with unsupported hardware keys

Sources/xcodes/App.swift
Resolves https://github.com/XcodesOrg/xcodes/issues/236
If the specified version of Xcode was already installed, the `--select` flag was only respected in the variant that passed a version number.
`xcodes install 14.3.1 --select`
This PR fixes the `--select` flag for the other install cases.
`xcodes install --select`
`xcodes install --latest --select`
`xcodes install --latest-prerelease --select`
=> Always respect select flag during install

Sources/XcodesKit/Models+Runtimes.swift, Sources/XcodesKit/RuntimeInstaller.swift, Tests/XcodesKitTests/Fixtures/DownloadableRuntimes.plist, Tests/XcodesKitTests/Fixtures/LogOutput-Runtimes.txt, Tests/XcodesKitTests/RuntimeTests.swift
With introduction if Xcode 16 and iOS 18 simulators, a breaking change for xcodes was introduced through the simulators API. ("https://devimages-cdn.apple.com/downloads/xcode/simulators/index2.dvtdownloadableindex")
In order to keep current functionality working, I made 2 modifications:
1. Make runtime source optional. This is needed as iOS 18 downloadable does not have that value.
2. Add support for new `cryptexDiskImage` content type. As iOS 18 downloadable comes with new type of `contentType`, we should parse it in order to be able to process rest of the response.
In RuntimeInstaller, I've added logic to handle new optional and new content type be throwing error if those downloadable were to be used.
Test cases and fixtures were also updated to handle these new cases.
=> Quick fix to ignore new iOS 18 runtime downloadables

Package.resolved, Package.swift, Sources/AppleAPI/Client.swift, Sources/AppleAPI/URLRequest+Apple.swift, Sources/XcodesKit/Environment.swift
Apple switched up their login to now use a Secure Remote Password type of algorithm. This add support for it, so a user can login properly.
Fixes #388
=> Add support for SRP Apple login

Sources/XcodesKit/RuntimeInstaller.swift
This PR attempts to port the logic from https://github.com/XcodesOrg/XcodesApp/pull/622 to the CLI tool.
Fixes #384 
The logic in the `downloadAndInstallRuntime` was modified to now switch over the runtime's content type.  The previous existing package and disk image installs were left unchanged, but the `.cryptexDiskImage` case is now handled by the `downloadAndInstallUsingXcodeBuild` function.
This function does 3 main things (broken into some smaller helper functions for those).
1. Check that we're using a new enough version of Xcode
2. Start downloading using Xcodebuild and create an AsyncStream of the progress
3. Write out that progress to the console
In order to test this out you will need to have xcode 16.1 or newer installed.  
Things I tested and seemed to work for me:
1. try to …
=> Fixes iOS 18+ runtime downloads

Sources/AppleAPI/Client.swift, Tests/AppleAPITests/AppleAPITests.swift, Tests/AppleAPITests/Fixtures/Login_Service_Temporarily_Unavailable/AuthOptions.json, Tests/AppleAPITests/Fixtures/Login_Service_Temporarily_Unavailable/Federate.json, Tests/AppleAPITests/Fixtures/Login_Service_Temporarily_Unavailable/ITCServiceKey.json, Tests/AppleAPITests/Fixtures/Login_Service_Temporarily_Unavailable/OlympusSession.json, Tests/AppleAPITests/Fixtures/Login_Service_Temporarily_Unavailable/SignIn.json
If Apple server response html format, Client can not decode response as JSON.
So, In this case, Client just look status code and throw serviceTemporarilyUnavailable error instead json decode error.
Ref: https://github.com/XcodesOrg/xcodes/issues/388
Ref: https://github.com/XcodesOrg/XcodesApp/issues/630
=> Support Service Temporarily Unavailable response error

Sources/XcodesKit/Models+Runtimes.swift, Sources/XcodesKit/RuntimeInstaller.swift
If recent runtimes are installed (18.4, possibly 18.3.1), xcodes can no longer list (or install?) runtimes.
Resolves #421
=> Add support for local cryptex disk images

Sources/XcodesKit/Models+Runtimes.swift, Sources/XcodesKit/RuntimeInstaller.swift
This one's a fast-follow to #423. The just-released `iOS 26.0-beta1` runtime, when installed, reports its `kind` as `"Patchable Crypex Disk Image"`.
I also added an enum case to the runtime API endpoint's `contentType`, though I don't think that's strictly necessary—the API still parses fine as-is (i.e. the 26.0b1 runtimes are parsed as `cryptexDiskImage`)
=> Add patchable cryptex disk image handling
